### ISSUE TITLE
zedcloud_edgeapp_instance custom variables cannot be used properly

### ISSUE THREAD

**Issue by erkki** [zededa/terraform-provider-zedcloud#28]
Right now custom variables can be set for `zedcloud_edgeapp_instance` on resource creation:
Eg:

```hcl
custom_config {
  variable_group {
    name = "cloud-init"
      variable {
        encode   = "FILE_ENCODING_UNSPECIFIED"
        format   = "VARIABLE_FORMAT_TEXT"
        label    = "custom-var-1"
        name     = "custom-var-1"
        required = true
        value    = "variable-value"
     }
  }
}
```

This works and the resource creation is successful.

Afterwards, though, on update these variables cannot be read back from the API.
What this means is that the desired state is never reconciled, subsequent `terraform plan` invocations always see a change needing to be applied, without ever resulting to a reconciled state.

Any pointers for correct usage here?

**Comment by kalyan-nidumolu** [comment]
Hmm.. Thanks for pointing this out. Let me take a look and get back to you.

**Comment by fabian-zededa** [comment]
Fixed in v2
