### ISSUE TITLE
cannot create an edge node which has been offboarded

### ISSUE THREAD

**Issue by erkki** [zededa/terraform-provider-zedcloud#29]
It's seemingly not possible to create an edge node (again) after it has been onboarded once (initially) and then offboarded.

This type of activity is common in testing automation workflows on the same physical edge node.

Output:
```
zedcloud_edgenode.<node>: Creating...
╷
│ Error: [ERROR] EdgeNode <node> ( id: ) Create Failed. err: Request FAILED. StatusCode: 409 Conflict
│ Request Failed. HTTPStatusCode: 409, HTTPStatusMsg:  ErrorCode: AlreadyExists, ErrorDetails: Entry already exists
│ 
│ 
│   with zedcloud_edgenode.<node>,
│   on <node>.tf line 1, in resource "zedcloud_edgenode" "<node>":
│    1: resource "zedcloud_edgenode" "<node>" {
│ 
╵
```

The same procedure works for example when re-creating the node again with `zcli edge-node create`.

**Comment by kalyan-nidumolu** [comment]
Hi Erkki, When you say offboarded + re-create, are you referring to "delete + re-create" ? There is a "Offboard" operation which is seperate from delete. We do not currently support Offboard in Terraform.

If you are referring to "Create + Delete + Create" - This should work. In your case, did delete fail by any chance?

**Comment by erkki** [comment]
Hi

1) create a new node with terraform (or import an existing node -- don't remember  which way it was)
2) create dependent resources (volume instances, network instances) with terraform
3) do a `terraform state rm`
4) manually clean up dependent resources in  the UI
5) `offboard`the node in the UI.
6) Apply  the terraform resources in 1) again => 409

I didn't yet manage to see what terraform does differently  compared to zcli, as the same command used to initially `create` the edgenode in cli continues to work (even though after offboarding it is not a create anymore as the object uuid stays the same).

Does this make sense?

**Comment by erkki** [comment]
As to the usecase -- we did this to test initial automation steps  on the same hardware without  having to  actually reinstall the OS (which would be mandated if we were to use delete).

**Comment by kalyan-nidumolu** [comment]
Then the Terraform provider is doing what it is expected to do.

Step 5 (offboardthe node in the UI) - This does not actually delete the
node from ZEDCloud. So when you try to recreate it, it will fail.
I assume you want to actually do delete + create? That would work - but
would need re-install of EVE to make it register again.

Offboard workflow is currently not supported by terraform. This would be a
new feature.

Thanks,
Kalyan

**Comment by erkki** [comment]
Yep, I get it.

How is that different from zcli though, from an API perspective?

Right now we're basically using the workaround of "create the  node again with zcli, import to terraform, continue the rest with terraform", but that breaks a quick dev-test feedback loop.

Happy to make this a feature request instead.

Repurpose this ticket or make a new one?

**Comment by fabian-zededa** [comment]
closed due to inactivity.
