### ISSUE TITLE
change detection broken for zedcloud_edgeapp + manifest_file

### ISSUE THREAD

**Issue by erkki** [zededa/terraform-provider-zedcloud#32]
When `manifest_file` is used to create an `zedcloud_edgeapp` instance, subsequent changes to the json content of `manifest_file` or changes to the manifest on ZedCloud side do not get reflected in `terraform plan`.

At the same time, changing data in the json definition file **together with** another attribute  in `zedcloud_edgeapp` persists the changes from the json file as well.

This in general breaks the principle of least surprise and goes against terraform remote state tracking philosophy.

**Comment by kalyan-nidumolu** [comment]
This is expected. The contents of the file is not managed by terraform. 
Use "manifest" field instead (In EdgeApp). This allows the App Manifest to be managed as part of terraform App resource. 

Note - You can either use manifest_file or manifest - not both.
We are planning to deprecate "manifest_file" option in future releases.

**Comment by fabian-zededa** [comment]
@erkki v2 has full support for the manifest definition in the config file. It still supports reading the manifest file but it is not recommended for the reasons mentioned.

**Comment by erkki** [comment]
yep agreed, manifest definition is better way, we shall migrate our usage too
