### ISSUE TITLE
eve_image_version is optional for resource zedcloud_edgenode on the documentation

### ISSUE THREAD

**Issue by bayupw** [zededa/terraform-provider-zedcloud#44]
The argument `eve_image_version` is optional for resource `zedcloud_edgenode` on the documentation https://registry.terraform.io/providers/zededa/zedcloud/latest/docs/resources/edgenode

However, terraform will throw an error
`Error: [ERROR] EdgeNode eve-vm1 ( id: ) Create Failed. Error: eve_image_version must be specified.`     

I can successfully onboarding Edge Node via UI and zCLI (`zcli edge-node create`) without specifying eve image version
Ideally the terraform have the same arguments or parameters for onboarding Edge Node.
Would be good to update the document to mark which arguments are mandatory and which are optional.

**Comment by fabian-zededa** [comment]
@bayupw this is fixed in v2. The currently required fields are the ones in this test case: https://github.com/zededa/terraform-provider-zedcloud/blob/main/resources/testdata/node/create_required_only.tf
