### ISSUE TITLE
Feature Request: Resource and Data Source for project_id

### ISSUE THREAD

**Issue by bayupw** [zededa/terraform-provider-zedcloud#45]
Looking for a way to create or at least retrieve existing project_id via terraform
Ideally similar to zCLI:
`zcli> zcli project create my-first-project`
`zcli> zcli network create <name> --project=my-first-project ...`

Something like below:
```
resource "zedcloud_project_id" "my_project" {
    name = "my-first-project"
    ...
}

resource "zedcloud_network" "my_network" {
    project_id = zedcloud_project_id.my_project.uuid
    ...
}

resource "zedcloud_edgenode" "edge_node1" {
    project_id = zedcloud_project_id.my_project.uuid 
    name = "edgenode1"
    ...
}
```

What we would like to achieve is to provision end-to-end from scratch via terraform starting with creating project, networks, data store, and so on

**Comment by fabian-zededa** [comment]
@bayupw this is one of the next features on the agenda to implement. I will give you an update here once it's implemented.

**Comment by fabian-zededa** [comment]
@bayupw this has been added in [v2.2.1-beta](https://github.com/zededa/terraform-provider-zedcloud/releases/tag/v2.2.1-beta)
