### ISSUE TITLE
Cannot create resource zedcloud_network_instance. [ERROR]Failed to unmarshal response body. err: invalid character 'B' looking for beginning of value

### ISSUE THREAD

**Issue by avx-bwibowo** [zededa/terraform-provider-zedcloud#46]
I'm running a simple create resource zedcloud_network_instance and receiving below error.

```
Error: [ERROR] NetworkInstance edge001-switch-eth0 ( id: ) Create Failed. Request FAILED. StatusCode: 400 Bad Request
│ ***[ERROR]Failed to unmarshal response body. err: invalid character 'B' looking for beginning of value
│ rsp body: Bad Request
│ {"operationType":"OPS_TYPE_UNSPECIFIED","operationStatus":"OPS_STATUS_UNSPECIFIED","objectKind":"","objectId":"","objectName":"","objectRevision":"","objectType":"OBJECT_TYPE_UNSPECIFIED","operationTime":"","startTime":"","endTime":"","user":"","httpStatusCode":400,"httpStatusMsg":"failed to parse json request body: proto: (line 1:183): invalid value for enum type: \"\"","jobId":"","error":[{"ec":"BadReqBody","location":"","details":"request body parsing failed"}]}
```

I can create from ZedControl UI fine with below 7 fields/arguments:
1. Name
2. Title
3. Description
4. Kind = Switch
5. edge node = edge node is online
6. port = eth0
7. Default Edge Node Network Instance = unticked

Is there anything I missed in my Terraform code?
I couldn't find info on the [documentation](https://registry.terraform.io/providers/zededa/zedcloud/latest/docs/resources/network_instance) on which field are mandatory vs optional. 
Below is my code

```
resource "zedcloud_edgenode" "this" {
  ...
}

resource "zedcloud_network_instance" "eth0" {
  name           = "edge001-switch-eth0"
  title          = "edge001-switch-eth0"
  description    = "Switch network instance for edge001 eth0"
  kind           = "NETWORK_INSTANCE_KIND_SWITCH"
  device_id      = zedcloud_edgenode.this.id
  port           = "eth0"
  device_default = false
}
```

**Comment by fabian-zededa** [comment]
@avx-bwibowo this is supported now in v2. Please have a look for supported fields in this test case's config: https://github.com/zededa/terraform-provider-zedcloud/blob/main/resources/testdata/network_instance/create_complete.tf
