### ISSUE TITLE
Sample resource edgeapp_instance code with a cloud-init as custom config

### ISSUE THREAD

**Issue by bayupw** [zededa/terraform-provider-zedcloud#47]
Is there any sample code on how to use [resource edgeapp_instance] (https://registry.terraform.io/providers/zededa/zedcloud/latest/docs/resources/edgeapp_instance) with a cloud-init text as custom config especially the `custom_config` block?

I would like to create Edge App instance with terraform where I input a custom config similar to this guide https://help.zededa.com/hc/en-us/articles/4440323189403-Custom-Configuration-Edge-Application

Tried something like below but it didn't work for me
```
resource "zedcloud_edgeapp_instance" "this" {
  ...
  custom_config {
    add  = true
    name = "cloud-init"
    variable_group {
      name ="variablegroup"
      required = true
      variable {
        name ="cloud-init-variable"
        required = true
        format = "VARIABLE_FORMAT_TEXT"
        value  = var.custom_script
      }
    }
  }
```

**Comment by fabian-zededa** [comment]
@bayupw this is supported now in v2. Please have a look at this test case that shows an example: https://github.com/zededa/terraform-provider-zedcloud/blob/main/resources/testdata/application/create.tf#L16. I close the issue, please open a new one if this doesn't cover your case.
