### ISSUE TITLE
Application Instance interfaces are broken

### ISSUE THREAD

**Issue by Rileyjs** [zededa/terraform-provider-zedcloud#88]
When using an application instance, the interface blocks are not processed.

resource "zedcloud_application_instance" "this" {
...
interfaces {
  intfname    = "value"
  netinstname = "value"
  privateip   = "value"
}
...
}

Results in no change detected when planning or applying, due to the line found here [DiffSuppressFunc: supress(),](https://github.com/zededa/terraform-provider-zedcloud/blob/main/schemas/application_instance.go#L595).  That function always returns true, so all differences are ignored.  This change was applied in the last update, and related tests appear to have been commented out.

**Comment by fabian-zededa** [comment]
@Rileyjs fixed in v2.2.3-beta
